name: Build and Deploy Nginx

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev
          docker build -t us-east4-docker.pkg.dev/$GOOGLE_PROJECT/nodejs-repo/nginx:latest .
          docker push us-east4-docker.pkg.dev/$GOOGLE_PROJECT/nodejs-repo/nginx:latest

      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials nodejs-cluster1 --region us-east4
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
          kubectl apply -f resources.yaml
